#!/bin/sh
exec 2>&1

exec envuidgid curvedns envdir /etc/curvedns/env sh -c '

  if [ x"${IP}" = x ]; then
    echo "\$IP not set"; exit 111
  fi
  if [ x"${PORT}" = x ]; then
    echo "\$PORT not set"; exit 111
  fi
  if [ x"${REMOTEIP}" = x ]; then
    echo "\$REMOTEIP not set"; exit 111
  fi
  if [ x"${REMOTEPORT}" = x ]; then
    echo "\$REMOTEPORT not set"; exit 111
  fi

  exec /usr/sbin/curvedns "${IP}" "${PORT}" "${REMOTEIP}" "${REMOTEPORT}"

