#!/bin/sh -e

deluser --remove-all-files curvedns

if [ -f /usr/sbin/curvedns ]; then
  rm /usr/sbin/curvedns
fi
if [ -f /usr/sbin/curvedns-keygen ]; then
  rm /usr/sbin-curvedns-keygen
fi

if [ -d /etc/curvedns/ ]; then
   rm -fr /etc/curvedns/
fi

if [ -d /var/log/curvedns/ ]; then
   rm -fr /var/log/curvedns/
fi


