#!/bin/sh -e
set -e

if [ x"$1" != "xpurge" ]; then
    exit 0
fi

deluser --force curvedns 
deluser --force curvednslog

rm /etc/default/curvedns
rm -rf /var/log/curvedns /etc/curvedns

#DEBHELPER#



