#!/bin/sh -e

if ! /usr/bin/getent group curvedns > /dev/null 2>&1; then
  addgroup --quiet --system curvedns >/dev/null
fi
if ! /usr/bin/getent passwd curvedns > /dev/null 2>&1; then
   /usr/sbin/adduser --quiet --system --home /etc/curvedns --ingroup curvedns -no-create-home --shell /bin/false curvedns
fi
/bin/chown curvedns:curvedbs -R /etc/curvedns /var/log/curvedns


if [ -d /etc/curvedns/env ]; then
   /bin/chmod 0700 /etc/curvedns/env
fi


if [ -d /var/log/curvedns/ ]; then
   /bin/chown curvedns:root /var/log/curvedns/
fi
