#!/bin/sh

# we cannot pass the required environment options to the curvedns daemon using
# start-stop-daemon; instead we call this wrapper script which ensures that the
# environment variables required by the daemon are available before execing it
set -o allexport
. /etc/default/curvedns
. /etc/curvedns/curvedns_private_key.hex
. /var/lib/curvedns/numeric_uid_gid
exec /usr/sbin/curvedns "$@"

